# Generated by Django 4.0.2 on 2023-06-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_number', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('maintenance', 'Maintenance')], max_length=12)),
                ('current_floor', models.IntegerField(default=0)),
                ('destination_floor', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=5)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevators.elevator')),
            ],
        ),
    ]
